/**
 * Standalone Exporter Utility (v2.1)
 * Bundles scene data and assets into a portable distribution folder.
 */
class Exporter {
  SceneManager scene;
  
  Exporter(SceneManager sc) {
    this.scene = sc;
  }
  
  void build(String projectPath) {
    println("--- START STANDALONE BUILD ---");
    File buildDir = new File(projectPath);
    if (!buildDir.exists()) buildDir.mkdirs();
    
    File dataDir = new File(projectPath, "data");
    if (!dataDir.exists()) dataDir.mkdirs();
    
    // 1. Collect and Copy Assets
    HashMap<String, String> pathMap = new HashMap<String, String>(); // Absolute -> Relative
    
    for (Entity e : scene.entities) {
      if (!e.modelPath.isEmpty()) {
        String rel = "models/" + getFileName(e.modelPath);
        copyAsset(e.modelPath, new File(dataDir, rel).getAbsolutePath());
        pathMap.put(e.modelPath, rel);
      }
      
      Material m = e.material;
      if (!m.albedoPath.isEmpty()) {
        String rel = "textures/" + getFileName(m.albedoPath);
        copyAsset(m.albedoPath, new File(dataDir, rel).getAbsolutePath());
        pathMap.put(m.albedoPath, rel);
      }
      if (!m.metallicPath.isEmpty()) {
        String rel = "textures/" + getFileName(m.metallicPath);
        copyAsset(m.metallicPath, new File(dataDir, rel).getAbsolutePath());
        pathMap.put(m.metallicPath, rel);
      }
      if (!m.roughnessPath.isEmpty()) {
        String rel = "textures/" + getFileName(m.roughnessPath);
        copyAsset(m.roughnessPath, new File(dataDir, rel).getAbsolutePath());
        pathMap.put(m.roughnessPath, rel);
      }
    }
    
    // 2. Generate portable scene JSON
    JSONObject root = serializePortable(pathMap);
    p3deditor.this.saveJSONObject(root, new File(dataDir, "boot.p3djson").getAbsolutePath());
    
    // 3. Copy Core Engine Source
    copyEngineSource(projectPath);
    
    // 4. Generate Main Player Entry
    String projectName = new File(projectPath).getName();
    generatePlayerPDE(projectPath, projectName);
    
    println("SUCCESS: Build exported to " + projectPath);
  }
  
  // Custom serialization that replaces absolute paths with relative ones for the build
  JSONObject serializePortable(HashMap<String, String> pathMap) {
    JSONObject root = new JSONObject();
    root.setInt("nextEntityId", scene.nextEntityId);
    
    JSONArray entArr = new JSONArray();
    for (int i=0; i<scene.entities.size(); i++) {
      Entity e = scene.entities.get(i);
      JSONObject ej = e.toJSON(); // Start with standard JSON
      
      // Override absolute paths with relative ones for the build subfolder
      if (pathMap.containsKey(e.modelPath)) {
        ej.setString("modelPath", "data/" + pathMap.get(e.modelPath));
      }
      
      JSONObject mat = ej.getJSONObject("material");
      if (mat != null) {
        if (pathMap.containsKey(e.material.albedoPath)) mat.setString("albedoPath", "data/" + pathMap.get(e.material.albedoPath));
        if (pathMap.containsKey(e.material.metallicPath)) mat.setString("metallicPath", "data/" + pathMap.get(e.material.metallicPath));
        if (pathMap.containsKey(e.material.roughnessPath)) mat.setString("roughnessPath", "data/" + pathMap.get(e.material.roughnessPath));
      }
      
      entArr.setJSONObject(i, ej);
    }
    root.setJSONArray("entities", entArr);
    return root;
  }
  
  void copyAsset(String src, String dest) {
    File srcF = new File(src);
    if (!srcF.exists()) {
       println("WARNING: Source asset missing: " + src);
       return;
    }
    
    File destF = new File(dest);
    if (!destF.getParentFile().exists()) destF.getParentFile().mkdirs();
    
    println("Copying: " + srcF.getName() + " -> " + dest);
    // Simple Processing helper to handle byte copying
    byte[] b = p3deditor.this.loadBytes(src);
    if (b != null) p3deditor.this.saveBytes(dest, b);
  }
  
  void copyEngineSource(String destPath) {
    String[] coreFiles = {
      "SceneManager.pde", "Entity.pde", "Material.pde", "Raycast.pde", 
      "ScriptEngine.pde", "Command.pde", "CommandInterpreter.pde", "OSCClient.pde"
    };
    
    for (String f : coreFiles) {
      String src = p3deditor.this.sketchPath(f);
      copyAsset(src, new File(destPath, f).getAbsolutePath());
    }
    
    // Copy Shaders
    copyAsset(sketchPath("data/pbr.frag"), new File(destPath, "data/pbr.frag").getAbsolutePath());
    copyAsset(sketchPath("data/pbr.vert"), new File(destPath, "data/pbr.vert").getAbsolutePath());
  }
  
  void generatePlayerPDE(String folderPath, String projectName) {
    String filename = projectName + ".pde";
    String[] code = {
      "/**",
      " * P3DE Standalone Player",
      " * Auto-generated by P3D Editor Exporter v2.1",
      " */",
      "SceneManager scene;",
      "Raycaster raycaster;",
      "ScriptManager scriptManager;",
      "CommandInterpreter interpreter;",
      "OSCClient oscClient = new OSCClient();",
      "PShader pbrShader;",
      "PFont mainFont;",
      "PMatrix3D savedProj = new PMatrix3D();",
      "PMatrix3D savedView = new PMatrix3D();",
      "boolean showUI = false;",
      "",
      "void setup() {",
      "  size(1280, 720, P3D);",
      "  hint(ENABLE_TEXTURE_MIPMAPS);",
      "  mainFont = createFont(\"SansSerif\", 12, true);",
      "  textFont(mainFont);",
      "  ",
      "  scene = new SceneManager();",
      "  interpreter = new CommandInterpreter(scene);",
      "  raycaster = new Raycaster();",
      "  scriptManager = new ScriptManager(interpreter);",
      "  interpreter.setScriptManager(scriptManager);",
      "  ",
      "  pbrShader = loadShader(\"data/pbr.frag\", \"data/pbr.vert\");",
      "  ",
      "  scene.loadScene(\"data/boot.p3djson\");",
      "  scene.engineMode = 2; // MODE_GAME",
      "}",
      "",
      "void draw() {",
      "  background(0);",
      "  if (scriptManager != null) scriptManager.update();",
      "  ",
      "  // Matrix sync for Raycasting",
      "  savedProj.set(((PGraphics3D)g).projection);",
      "  savedView.set(((PGraphics3D)g).modelview);",
      "  ",
      "  scene.render();",
      "}",
      "",
      "void mousePressed() {",
      "  Ray ray = raycaster.getPickRay(mouseX, mouseY, width, height, savedProj, savedView);",
      "  Entity hit = scene.pickEntity(ray, raycaster);",
      "  if (hit != null) {",
      "    scene.triggerEvent(hit, \"onClick\");",
      "  }",
      "}",
      "",
      "void keyPressed() {",
      "  if (key == ESC) {",
      "    exit();",
      "  }",
      "}"
    };
    
    p3deditor.this.saveStrings(new File(folderPath, filename).getAbsolutePath(), code);
  }

  String getFileName(String path) {
    int last = max(path.lastIndexOf('/'), path.lastIndexOf('\\'));
    if (last == -1) return path;
    return path.substring(last + 1);
  }
}
